version: "3.9"

services:
  # React frontend service
  balinkbayan:
    build: .
    container_name: balinkbayan
    ports:
      - "4173:4173"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.balinkbayan.rule=Host(`ec2-54-206-34-35.ap-southeast-2.compute.amazonaws.com`)"
      - "traefik.http.services.balinkbayan.loadbalancer.server.port=4173"

  # Traefik reverse proxy service
  traefik:
    image: traefik:v2.7
    container_name: traefik
    command:
      - "--api.insecure=true" # Enable Traefik dashboard (insecure)
      - "--providers.docker=true" # Use Docker provider
      - "--entryPoints.web.address=:80" # Expose HTTP on port 80
    ports:
      - "80:80" # Expose port 80 (HTTP)
      - "8080:8080" # Expose Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Access Docker socket for Traefik to manage containers
