import type { optional } from "../types";

export const china: optional[] = [
  {
    country: 'China',
    name: 'EMBASSY OF THE PHILIPPINES, BEIJING',
    headOffice1: 'H.E. (Ms.) Sonia C. Brady',
    headOffice2: 'Ambassador Extraordinary and Plenipotentiary',
    address: '23 Xiu Shui Bei Jie, Jian Guo Men Wai, Beijing, 100600 People’s Republic of China',
    email1: 'beijing.pe@dfa.gov.ph;',
    email2: 'philemb_beijing@yahoo.com',
    website: 'https://www.philembassychina.org',
  },
  {
    name: 'PHILIPPINE CONSULATE GENERAL, CHONGQING',
    headOffice1: 'Hon. (Ms.) Amelita C. Aquino',
    headOffice2: 'Consul General',
    address: 'Unit 2903-05 Metropolitan Tower, 68 Zourong Road, Yuzhong District, Chongqing 400010, People’s Republic of China',
    email1: 'chongqing.pcg@dfa.gov.ph;',
    email2: 'chongqingpcg@gmail.com',
    website: 'https://www.philcongenchongqing.com',
  },
  {
    name: 'PHILIPPINE CONSULATE GENERAL, GUANGZHOU',
    headOffice1: 'Hon. (Mr.) Raly L. Tejada',
    headOffice2: 'Consul General',
    address: 'Room Nos. 706-712 Guangdong International Hotel 339 Huanshi Dong Lu, Guangzhou, Guangdong, 510098 P.R.O.C.',
    email1: 'guangzhou.pcg@dfa.gov.ph;',
    email2: 'post@guangzhoupcg.org;',
    email3: 'philcongenguangzhou@yahoo.com',
    website: 'https://www.philcongenguangzhou.org',
  },
  {
    name: 'PHILIPPINE CONSULATE GENERAL, HONG KONG',
    headOffice1: 'Hon. (Mr.) Noel Eugene Eusebio M. Servigon',
    headOffice2: 'Consul General',
    address: '14th Floor, United Centre, 95 Queensway Admiralty, Hong Kong SAR',
    email1: 'hongkong.pcg@dfa.gov.ph;',
    email2: 'hongkongpc@philcongen-hk.com',
    website: 'http://www.philcongen-hk.com',
  },
  {
    name: 'PHILIPPINE CONSULATE GENERAL, MACAU',
    headOffice1: 'Hon. (Mr.) Danilo T. Ibayan',
    headOffice2: 'Consul General',
    address: 'Units 1404-1406, 14/F AIA Tower, Avenida Comercial de Macau, Macau SAR',
    email1: 'macau.pcg@dfa.gov.ph;',
    email2: 'info@philcongenmacau.org;',
    email3: 'pcgmacau@gmail.com',
    website: 'https://www.philcongenmacau.org',
  },
  {
    name: 'PHILIPPINE CONSULATE GENERAL, SHANGHAI',
    headOffice1: 'Hon. (Mr.) Charles C. Jose',
    headOffice2: 'Consul General',
    address: 'Suite 301 Metrobank Plaza 1160 Yan An West Road, Changning District, Shanghai, China 200052',
    email1: 'shanghai.pcg@dfa.gov.ph;',
    email2: 'pcg@philcongenshanghai.org',
    website: 'https://www.philcongenshanghai.org',
  },
  {
    name: 'PHILIPPINE CONSULATE GENERAL, XIAMEN',
    headOffice1: 'Hon. (Mr.) Adelio Angelito C. Cruz',
    headOffice2: 'Consul General',
    address: 'No. 2 Ling Xiang Li, Lianhua District, Xiamen City 361009 People’s Republic of China',
    email1: 'xiamen.pcg@dfa.gov.ph;',
    email2: 'xiamenpc@yahoo.com',
    website: 'https://www.philcongenxiamen.com',
  },
];