import type { optional } from "../types";

export const spain: optional[] = [
  {
    country: "Spain",
    name: "EMBASSY OF THE PHILIPPINES, MADRID",
    headOffice1: "H.E. (Mr.) Carlos C. Salinas",
    headOffice2: "Ambassador Extraordinary and Plenipotentiary",
    address: "Calle Eresma 2 (Chancery)",
    address2: "Calle Guadalquivir 6 (Consular Section) 28002 Madrid, Spain",
    email1: "madridpe@dfa.gov.ph;",
    email2: "madridpe@terra.es;",
    email3: "madridpe@yahoo.com;",
    email4: "consular@madridpe.org",
    website: "https://www.philembassymadrid.com",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, PALMA DE MALLORCA",
    headOffice1: "Mr. Juan Torrente Blanch",
    headOffice2: "Consul General, ad honorem",
    address: "Calle Anselmo Clave No. 2, 2°-3° A, 07002 Palma de Mallorca, Islas Baleares",
    email1: "consultorrente@terra.es",
  },
  {
    name: "PHILIPPINE CONSULATE, BARCELONA",
    headOffice1: "Mr. Justo Rico Ferrer",
    headOffice2: "Vice Consul, ad honorem",
    address: "Calle Corsega No. 284, 1a 08008 Barcelona, Spain",
    email1: "jrico@tsth-itt.com",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, BILBAO",
    headOffice1: "Mr. Andoni de Irala Estevez",
    headOffice2: "Consul General, ad honorem",
    address: "Calle Diputacion 8, 3° Oficina 1, 48008 Bilbao Bizkaia",
    email1: "andonideirala@gmail.com",
  },
  {
    name: "PHILIPPINE CONSULATE, CADIZ",
    headOffice1: "Mr. Fernando Javier Blanco Martin",
    headOffice2: "Consul, ad honorem",
    address: "Calle Pintor Zuloaga 22, 4° B, 11006 Cadiz",
    email1: "philconcadiz@gmail.com",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, SANTIAGO DE COMPOSTELA",
    headOffice1: "Hon. (Mr.) Elias F. Lamelas",
    headOffice2: "Consul General, ad honorem",
    address: "Rua do vilar 46, 2° derecha, 15705 Santiago de Compostela Galicia, Spain",
    email1: "eliaslamelas@gmail.com",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, SEVILLA",
    headOffice1: "Hon. (Mr.) Jose Ignacio Bidon y Vigil de Quinones",
    headOffice2: "Consul General, ad honorem",
    address: "Avda. de La Palmera No. 8, 41012 Sevilla",
    email1: "consulfilipinasbidon@gmail.com",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, VALENCIA",
    headOffice1: "Hon. (Ms.) Maria Carmen Sanchis",
    headOffice2: "Consul General, ad honorem",
    headOffice3: "Mr. Vicente Sanchis Ferrandis",
    headOffice4: "Vice Consul, a.h.",
    address: "Avda. del Puerto, 308-1° Piso, Puerto 3, 46024 Valencia, Spain",
    email1: "mcsanchis@gmail.com",
    email2: "vetesanchis@hotmail.com",
  },
];