import type { optional } from "../types";

export const unitedStatesOfAmerica: optional[] = [
  {
    country: "USA",
    name: "EMBASSY OF THE REPUBLIC OF THE PHILIPPINES, WASHINGTON",
    headOffice1: "H.E. (Mr.) Jose L. Cuisia, Jr.",
    headOffice2: "Ambassador Extraordinary and Plenipotentiary",
    address: "1600 Massachusetts Avenue NW, Washington, D.C. 20036, U.S.A.",
    email1: "washington.pe@dfa.gov.ph;",
    email2: "washingtonpe@philippinesusa.org;",
    email3: "washingtonpe2010@gmail.com",
    website: "https://www.philippineembassy-usa.org",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, AGANA",
    headOffice1: "Hon. (Mr.) Bayani V. Mangibin",
    headOffice2: "Consul General",
    address: "Suite 601-602, ITC Building, Marine Drive, Tamuning, Guam 96913",
    email1: "agana.pcg@dfa.gov.ph;",
    email2: "pcgagana@gmail.com",
    website: "https://www.philippinesguam.org",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, ATLANTA",
    headOffice1: "Mr. Raoul R. Donato",
    headOffice2: "Consul General, ad honorem",
    address: "3340 Peach Tree Road NE, Suite 850, Atlanta, Georgia 30326",
    email1: "donato@ahdintl.com",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, CHARLOTTE-AMALIE (U.S. VIRGIN ISLANDS)",
    headOffice1: "Mr. Vicente F. Poblete, Jr.",
    headOffice2: "Consul General, ad honorem",
    address: "P.O. Box 12154, Charlotte-Amalie Street Thomas, U.S. Virgin Islands 00801",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, CHICAGO",
    headOffice1: "Hon. (Mr.) Leo Herrera-Lim",
    headOffice2: "Consul General",
    address: "30 N. Michigan Avenue, Suite 2100 Chicago, Illinois 60602 USA",
    email1: "chicago.pcg@dfa.gov.ph;",
    email2: "chicagopcg@pcgchicago.comcastbiz.net",
    website: "https://www.chicagopcg.dfa.gov.ph; ",
    website2: "https://www.chicagopcg.com",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, FORT LAUDERDALE",
    headOffice1: "Dr. Angelo S. Macatangay, Jr.",
    headOffice2: "Consul General, ad honorem",
    address: "Southport Plaza,1635 Miami Road, Suite #3,Fort Lauderdale, Florida 33316",
    email1: "ConsulGeneralFlorida@yahoo.com",
    website: "https://www.philippineconsulateofsouthflorida.cc",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, HONOLULU",
    headOffice1: "Hon. (Mr.) Julius D. Torres",
    headOffice2: "Consul General",
    address: "2433 Pali Highway, Honolulu Hawaii 96817, U.S.A.",
    email1: "honolulu.pcg@dfa.gov.ph; pc.honolulu@dfa.gov.ph; honolulupc@hawaii.rr.com",
    website: "https://www.honolulupcg.dfa.gov.ph;",
    website2: "https://www.philippinehonolulu.com",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, LIVONIA (MICHIGAN)",
    headOffice1: "Dr. Jose L. Evangelista",
    headOffice2: "Consul General, ad honorem",
    address: "10475 Farmington Road, Livonia, Michigan, 48150",
    email1: "evangeljose@aol.com",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, LOS ANGELES",
    headOffice1: "Hon. (Ms.) Maria Hellen B. De La Vega",
    headOffice2: "Consul General",
    address: "3600 Wilshire Boulevard, Suite 500 Los Angeles, CA 90010 U.S.A.",
    email1: "losangeles.pcg@dfa.gov.ph; losangelespc@aol.com; losangelespcg@earthlink.net",
    website: "https://www.philippineconsulatela.org",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, NEW YORK",
    headOffice1: "Hon. (Mr.) Mario L. De Leon, Jr.",
    headOffice2: "Consul General",
    address: "556 Fifth Avenue, New York, NY 10036 U.S.A.",
    email1: "newyork.pcg@dfa.gov.ph; phcongen.newyork@gmail.com",
    website: "https://www.newyorkpcg.org",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, PORTLAND",
    headOffice1: "Mr. Richard Woodling",
    headOffice2: "Consul General, ad honorem",
    address: "2662 SW Georgian Place, Portland, Oregon 97201 USA",
    email1: "richard.woodling@comcast.net",
  },
  {
    name: "PHILIPPINE CONSULATE GENERAL, SAN FRANCISCO",
    headOffice1: "Hon. (Mr.) Marciano A. Paynor, Jr.",
    headOffice2: "Consul General",
    address: "447 Sutter Street, 6th Floor, San Francisco, California 94108, U.S.A.",
    email1: "sanfrancisco.pcg@dfa.gov.ph; sanfranciscopcg2004@yahoo.com",
    website: "https://www.pcgSanFrancisco.org;",
    website2: "http://www.philippinessanfrancisco.org/",
  },
];