/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as publicpImport } from './routes/(public)/__p'
import { Route as protectedprotectedImport } from './routes/(protected)/__protected'
import { Route as authauthImport } from './routes/(auth)/__auth'
import { Route as publicpIndexImport } from './routes/(public)/__p.index'
import { Route as authauthLoginImport } from './routes/(auth)/__auth.login'
import { Route as publicpStartBusinessIndexImport } from './routes/(public)/__p.start-business/index'
import { Route as publicpServicesIndexImport } from './routes/(public)/__p.services/index'
import { Route as publicpNewsIndexImport } from './routes/(public)/__p.news/index'
import { Route as publicpDownloadsIndexImport } from './routes/(public)/__p.downloads/index'
import { Route as publicpDonateIndexImport } from './routes/(public)/__p.donate/index'
import { Route as publicpContactIndexImport } from './routes/(public)/__p.contact/index'
import { Route as protectedprotectedCmsIndexImport } from './routes/(protected)/__protected.cms/index'
import { Route as publicpAboutCfoIndexImport } from './routes/(public)/__p.about/cfo/index'
import { Route as publicpAboutBalinkbayanIndexImport } from './routes/(public)/__p.about/balinkbayan/index'
import { Route as publicpStartBusinessInvestmentOpAgricultureImport } from './routes/(public)/__p.start-business/investment-op/agriculture'
import { Route as publicpStartBusinessSmallEnterpriseKnowledgeCenterStartABusinessThinkingAboutItImport } from './routes/(public)/__p.start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it'

// Create Virtual Routes

const publicImport = createFileRoute('/(public)')()
const protectedImport = createFileRoute('/(protected)')()
const authImport = createFileRoute('/(auth)')()

// Create/Update Routes

const publicRoute = publicImport.update({
  id: '/(public)',
  getParentRoute: () => rootRoute,
} as any)

const protectedRoute = protectedImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRoute,
} as any)

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const publicpRoute = publicpImport.update({
  id: '/__p',
  getParentRoute: () => publicRoute,
} as any)

const protectedprotectedRoute = protectedprotectedImport.update({
  id: '/__protected',
  getParentRoute: () => protectedRoute,
} as any)

const authauthRoute = authauthImport.update({
  id: '/__auth',
  getParentRoute: () => authRoute,
} as any)

const publicpIndexRoute = publicpIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicpRoute,
} as any)

const authauthLoginRoute = authauthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authauthRoute,
} as any)

const publicpStartBusinessIndexRoute = publicpStartBusinessIndexImport.update({
  id: '/start-business/',
  path: '/start-business/',
  getParentRoute: () => publicpRoute,
} as any)

const publicpServicesIndexRoute = publicpServicesIndexImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => publicpRoute,
} as any)

const publicpNewsIndexRoute = publicpNewsIndexImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => publicpRoute,
} as any)

const publicpDownloadsIndexRoute = publicpDownloadsIndexImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => publicpRoute,
} as any)

const publicpDonateIndexRoute = publicpDonateIndexImport.update({
  id: '/donate/',
  path: '/donate/',
  getParentRoute: () => publicpRoute,
} as any)

const publicpContactIndexRoute = publicpContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => publicpRoute,
} as any)

const protectedprotectedCmsIndexRoute = protectedprotectedCmsIndexImport.update(
  {
    id: '/cms/',
    path: '/cms/',
    getParentRoute: () => protectedprotectedRoute,
  } as any,
)

const publicpAboutCfoIndexRoute = publicpAboutCfoIndexImport.update({
  id: '/about/cfo/',
  path: '/about/cfo/',
  getParentRoute: () => publicpRoute,
} as any)

const publicpAboutBalinkbayanIndexRoute =
  publicpAboutBalinkbayanIndexImport.update({
    id: '/about/balinkbayan/',
    path: '/about/balinkbayan/',
    getParentRoute: () => publicpRoute,
  } as any)

const publicpStartBusinessInvestmentOpAgricultureRoute =
  publicpStartBusinessInvestmentOpAgricultureImport.update({
    id: '/start-business/investment-op/agriculture',
    path: '/start-business/investment-op/agriculture',
    getParentRoute: () => publicpRoute,
  } as any)

const publicpStartBusinessSmallEnterpriseKnowledgeCenterStartABusinessThinkingAboutItRoute =
  publicpStartBusinessSmallEnterpriseKnowledgeCenterStartABusinessThinkingAboutItImport.update(
    {
      id: '/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it',
      path: '/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it',
      getParentRoute: () => publicpRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/__auth': {
      id: '/(auth)/__auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authauthImport
      parentRoute: typeof authRoute
    }
    '/(protected)': {
      id: '/(protected)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedImport
      parentRoute: typeof rootRoute
    }
    '/(protected)/__protected': {
      id: '/(protected)/__protected'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedprotectedImport
      parentRoute: typeof protectedRoute
    }
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicImport
      parentRoute: typeof rootRoute
    }
    '/(public)/__p': {
      id: '/(public)/__p'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicpImport
      parentRoute: typeof publicRoute
    }
    '/(auth)/__auth/login': {
      id: '/(auth)/__auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authauthLoginImport
      parentRoute: typeof authauthImport
    }
    '/(public)/__p/': {
      id: '/(public)/__p/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicpIndexImport
      parentRoute: typeof publicpImport
    }
    '/(protected)/__protected/cms/': {
      id: '/(protected)/__protected/cms/'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof protectedprotectedCmsIndexImport
      parentRoute: typeof protectedprotectedImport
    }
    '/(public)/__p/contact/': {
      id: '/(public)/__p/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof publicpContactIndexImport
      parentRoute: typeof publicpImport
    }
    '/(public)/__p/donate/': {
      id: '/(public)/__p/donate/'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof publicpDonateIndexImport
      parentRoute: typeof publicpImport
    }
    '/(public)/__p/downloads/': {
      id: '/(public)/__p/downloads/'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof publicpDownloadsIndexImport
      parentRoute: typeof publicpImport
    }
    '/(public)/__p/news/': {
      id: '/(public)/__p/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof publicpNewsIndexImport
      parentRoute: typeof publicpImport
    }
    '/(public)/__p/services/': {
      id: '/(public)/__p/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof publicpServicesIndexImport
      parentRoute: typeof publicpImport
    }
    '/(public)/__p/start-business/': {
      id: '/(public)/__p/start-business/'
      path: '/start-business'
      fullPath: '/start-business'
      preLoaderRoute: typeof publicpStartBusinessIndexImport
      parentRoute: typeof publicpImport
    }
    '/(public)/__p/start-business/investment-op/agriculture': {
      id: '/(public)/__p/start-business/investment-op/agriculture'
      path: '/start-business/investment-op/agriculture'
      fullPath: '/start-business/investment-op/agriculture'
      preLoaderRoute: typeof publicpStartBusinessInvestmentOpAgricultureImport
      parentRoute: typeof publicpImport
    }
    '/(public)/__p/about/balinkbayan/': {
      id: '/(public)/__p/about/balinkbayan/'
      path: '/about/balinkbayan'
      fullPath: '/about/balinkbayan'
      preLoaderRoute: typeof publicpAboutBalinkbayanIndexImport
      parentRoute: typeof publicpImport
    }
    '/(public)/__p/about/cfo/': {
      id: '/(public)/__p/about/cfo/'
      path: '/about/cfo'
      fullPath: '/about/cfo'
      preLoaderRoute: typeof publicpAboutCfoIndexImport
      parentRoute: typeof publicpImport
    }
    '/(public)/__p/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it': {
      id: '/(public)/__p/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it'
      path: '/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it'
      fullPath: '/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it'
      preLoaderRoute: typeof publicpStartBusinessSmallEnterpriseKnowledgeCenterStartABusinessThinkingAboutItImport
      parentRoute: typeof publicpImport
    }
  }
}

// Create and export the route tree

interface authauthRouteChildren {
  authauthLoginRoute: typeof authauthLoginRoute
}

const authauthRouteChildren: authauthRouteChildren = {
  authauthLoginRoute: authauthLoginRoute,
}

const authauthRouteWithChildren = authauthRoute._addFileChildren(
  authauthRouteChildren,
)

interface authRouteChildren {
  authauthRoute: typeof authauthRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authauthRoute: authauthRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

interface protectedprotectedRouteChildren {
  protectedprotectedCmsIndexRoute: typeof protectedprotectedCmsIndexRoute
}

const protectedprotectedRouteChildren: protectedprotectedRouteChildren = {
  protectedprotectedCmsIndexRoute: protectedprotectedCmsIndexRoute,
}

const protectedprotectedRouteWithChildren =
  protectedprotectedRoute._addFileChildren(protectedprotectedRouteChildren)

interface protectedRouteChildren {
  protectedprotectedRoute: typeof protectedprotectedRouteWithChildren
}

const protectedRouteChildren: protectedRouteChildren = {
  protectedprotectedRoute: protectedprotectedRouteWithChildren,
}

const protectedRouteWithChildren = protectedRoute._addFileChildren(
  protectedRouteChildren,
)

interface publicpRouteChildren {
  publicpIndexRoute: typeof publicpIndexRoute
  publicpContactIndexRoute: typeof publicpContactIndexRoute
  publicpDonateIndexRoute: typeof publicpDonateIndexRoute
  publicpDownloadsIndexRoute: typeof publicpDownloadsIndexRoute
  publicpNewsIndexRoute: typeof publicpNewsIndexRoute
  publicpServicesIndexRoute: typeof publicpServicesIndexRoute
  publicpStartBusinessIndexRoute: typeof publicpStartBusinessIndexRoute
  publicpStartBusinessInvestmentOpAgricultureRoute: typeof publicpStartBusinessInvestmentOpAgricultureRoute
  publicpAboutBalinkbayanIndexRoute: typeof publicpAboutBalinkbayanIndexRoute
  publicpAboutCfoIndexRoute: typeof publicpAboutCfoIndexRoute
  publicpStartBusinessSmallEnterpriseKnowledgeCenterStartABusinessThinkingAboutItRoute: typeof publicpStartBusinessSmallEnterpriseKnowledgeCenterStartABusinessThinkingAboutItRoute
}

const publicpRouteChildren: publicpRouteChildren = {
  publicpIndexRoute: publicpIndexRoute,
  publicpContactIndexRoute: publicpContactIndexRoute,
  publicpDonateIndexRoute: publicpDonateIndexRoute,
  publicpDownloadsIndexRoute: publicpDownloadsIndexRoute,
  publicpNewsIndexRoute: publicpNewsIndexRoute,
  publicpServicesIndexRoute: publicpServicesIndexRoute,
  publicpStartBusinessIndexRoute: publicpStartBusinessIndexRoute,
  publicpStartBusinessInvestmentOpAgricultureRoute:
    publicpStartBusinessInvestmentOpAgricultureRoute,
  publicpAboutBalinkbayanIndexRoute: publicpAboutBalinkbayanIndexRoute,
  publicpAboutCfoIndexRoute: publicpAboutCfoIndexRoute,
  publicpStartBusinessSmallEnterpriseKnowledgeCenterStartABusinessThinkingAboutItRoute:
    publicpStartBusinessSmallEnterpriseKnowledgeCenterStartABusinessThinkingAboutItRoute,
}

const publicpRouteWithChildren =
  publicpRoute._addFileChildren(publicpRouteChildren)

interface publicRouteChildren {
  publicpRoute: typeof publicpRouteWithChildren
}

const publicRouteChildren: publicRouteChildren = {
  publicpRoute: publicpRouteWithChildren,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof publicpIndexRoute
  '/login': typeof authauthLoginRoute
  '/cms': typeof protectedprotectedCmsIndexRoute
  '/contact': typeof publicpContactIndexRoute
  '/donate': typeof publicpDonateIndexRoute
  '/downloads': typeof publicpDownloadsIndexRoute
  '/news': typeof publicpNewsIndexRoute
  '/services': typeof publicpServicesIndexRoute
  '/start-business': typeof publicpStartBusinessIndexRoute
  '/start-business/investment-op/agriculture': typeof publicpStartBusinessInvestmentOpAgricultureRoute
  '/about/balinkbayan': typeof publicpAboutBalinkbayanIndexRoute
  '/about/cfo': typeof publicpAboutCfoIndexRoute
  '/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it': typeof publicpStartBusinessSmallEnterpriseKnowledgeCenterStartABusinessThinkingAboutItRoute
}

export interface FileRoutesByTo {
  '/': typeof publicpIndexRoute
  '/login': typeof authauthLoginRoute
  '/cms': typeof protectedprotectedCmsIndexRoute
  '/contact': typeof publicpContactIndexRoute
  '/donate': typeof publicpDonateIndexRoute
  '/downloads': typeof publicpDownloadsIndexRoute
  '/news': typeof publicpNewsIndexRoute
  '/services': typeof publicpServicesIndexRoute
  '/start-business': typeof publicpStartBusinessIndexRoute
  '/start-business/investment-op/agriculture': typeof publicpStartBusinessInvestmentOpAgricultureRoute
  '/about/balinkbayan': typeof publicpAboutBalinkbayanIndexRoute
  '/about/cfo': typeof publicpAboutCfoIndexRoute
  '/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it': typeof publicpStartBusinessSmallEnterpriseKnowledgeCenterStartABusinessThinkingAboutItRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/__auth': typeof authauthRouteWithChildren
  '/(protected)': typeof protectedRouteWithChildren
  '/(protected)/__protected': typeof protectedprotectedRouteWithChildren
  '/(public)': typeof publicRouteWithChildren
  '/(public)/__p': typeof publicpRouteWithChildren
  '/(auth)/__auth/login': typeof authauthLoginRoute
  '/(public)/__p/': typeof publicpIndexRoute
  '/(protected)/__protected/cms/': typeof protectedprotectedCmsIndexRoute
  '/(public)/__p/contact/': typeof publicpContactIndexRoute
  '/(public)/__p/donate/': typeof publicpDonateIndexRoute
  '/(public)/__p/downloads/': typeof publicpDownloadsIndexRoute
  '/(public)/__p/news/': typeof publicpNewsIndexRoute
  '/(public)/__p/services/': typeof publicpServicesIndexRoute
  '/(public)/__p/start-business/': typeof publicpStartBusinessIndexRoute
  '/(public)/__p/start-business/investment-op/agriculture': typeof publicpStartBusinessInvestmentOpAgricultureRoute
  '/(public)/__p/about/balinkbayan/': typeof publicpAboutBalinkbayanIndexRoute
  '/(public)/__p/about/cfo/': typeof publicpAboutCfoIndexRoute
  '/(public)/__p/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it': typeof publicpStartBusinessSmallEnterpriseKnowledgeCenterStartABusinessThinkingAboutItRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cms'
    | '/contact'
    | '/donate'
    | '/downloads'
    | '/news'
    | '/services'
    | '/start-business'
    | '/start-business/investment-op/agriculture'
    | '/about/balinkbayan'
    | '/about/cfo'
    | '/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cms'
    | '/contact'
    | '/donate'
    | '/downloads'
    | '/news'
    | '/services'
    | '/start-business'
    | '/start-business/investment-op/agriculture'
    | '/about/balinkbayan'
    | '/about/cfo'
    | '/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it'
  id:
    | '__root__'
    | '/(auth)'
    | '/(auth)/__auth'
    | '/(protected)'
    | '/(protected)/__protected'
    | '/(public)'
    | '/(public)/__p'
    | '/(auth)/__auth/login'
    | '/(public)/__p/'
    | '/(protected)/__protected/cms/'
    | '/(public)/__p/contact/'
    | '/(public)/__p/donate/'
    | '/(public)/__p/downloads/'
    | '/(public)/__p/news/'
    | '/(public)/__p/services/'
    | '/(public)/__p/start-business/'
    | '/(public)/__p/start-business/investment-op/agriculture'
    | '/(public)/__p/about/balinkbayan/'
    | '/(public)/__p/about/cfo/'
    | '/(public)/__p/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRoute: typeof authRouteWithChildren
  protectedRoute: typeof protectedRouteWithChildren
  publicRoute: typeof publicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  authRoute: authRouteWithChildren,
  protectedRoute: protectedRouteWithChildren,
  publicRoute: publicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/(protected)",
        "/(public)"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/__auth"
      ]
    },
    "/(auth)/__auth": {
      "filePath": "(auth)/__auth.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/__auth/login"
      ]
    },
    "/(protected)": {
      "filePath": "(protected)",
      "children": [
        "/(protected)/__protected"
      ]
    },
    "/(protected)/__protected": {
      "filePath": "(protected)/__protected.tsx",
      "parent": "/(protected)",
      "children": [
        "/(protected)/__protected/cms/"
      ]
    },
    "/(public)": {
      "filePath": "(public)",
      "children": [
        "/(public)/__p"
      ]
    },
    "/(public)/__p": {
      "filePath": "(public)/__p.tsx",
      "parent": "/(public)",
      "children": [
        "/(public)/__p/",
        "/(public)/__p/contact/",
        "/(public)/__p/donate/",
        "/(public)/__p/downloads/",
        "/(public)/__p/news/",
        "/(public)/__p/services/",
        "/(public)/__p/start-business/",
        "/(public)/__p/start-business/investment-op/agriculture",
        "/(public)/__p/about/balinkbayan/",
        "/(public)/__p/about/cfo/",
        "/(public)/__p/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it"
      ]
    },
    "/(auth)/__auth/login": {
      "filePath": "(auth)/__auth.login.tsx",
      "parent": "/(auth)/__auth"
    },
    "/(public)/__p/": {
      "filePath": "(public)/__p.index.tsx",
      "parent": "/(public)/__p"
    },
    "/(protected)/__protected/cms/": {
      "filePath": "(protected)/__protected.cms/index.tsx",
      "parent": "/(protected)/__protected"
    },
    "/(public)/__p/contact/": {
      "filePath": "(public)/__p.contact/index.tsx",
      "parent": "/(public)/__p"
    },
    "/(public)/__p/donate/": {
      "filePath": "(public)/__p.donate/index.tsx",
      "parent": "/(public)/__p"
    },
    "/(public)/__p/downloads/": {
      "filePath": "(public)/__p.downloads/index.tsx",
      "parent": "/(public)/__p"
    },
    "/(public)/__p/news/": {
      "filePath": "(public)/__p.news/index.tsx",
      "parent": "/(public)/__p"
    },
    "/(public)/__p/services/": {
      "filePath": "(public)/__p.services/index.tsx",
      "parent": "/(public)/__p"
    },
    "/(public)/__p/start-business/": {
      "filePath": "(public)/__p.start-business/index.tsx",
      "parent": "/(public)/__p"
    },
    "/(public)/__p/start-business/investment-op/agriculture": {
      "filePath": "(public)/__p.start-business/investment-op/agriculture.tsx",
      "parent": "/(public)/__p"
    },
    "/(public)/__p/about/balinkbayan/": {
      "filePath": "(public)/__p.about/balinkbayan/index.tsx",
      "parent": "/(public)/__p"
    },
    "/(public)/__p/about/cfo/": {
      "filePath": "(public)/__p.about/cfo/index.tsx",
      "parent": "/(public)/__p"
    },
    "/(public)/__p/start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it": {
      "filePath": "(public)/__p.start-business/small-enterprise-knowledge-center/start-a-business/thinking-about-it.tsx",
      "parent": "/(public)/__p"
    }
  }
}
ROUTE_MANIFEST_END */
