/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StartBusinessIndexImport } from './routes/start-business/index'
import { Route as ServicesIndexImport } from './routes/services/index'
import { Route as NewsIndexImport } from './routes/news/index'
import { Route as DownloadsIndexImport } from './routes/downloads/index'
import { Route as DonateIndexImport } from './routes/donate/index'
import { Route as ContactIndexImport } from './routes/contact/index'
import { Route as AboutCfoIndexImport } from './routes/about/cfo/index'
import { Route as AboutBalinkbayanIndexImport } from './routes/about/balinkbayan/index'
import { Route as StartBusinessInvestmentOpAgricultureImport } from './routes/start-business/investment-op/agriculture'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StartBusinessIndexRoute = StartBusinessIndexImport.update({
  id: '/start-business/',
  path: '/start-business/',
  getParentRoute: () => rootRoute,
} as any)

const ServicesIndexRoute = ServicesIndexImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRoute,
} as any)

const NewsIndexRoute = NewsIndexImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRoute,
} as any)

const DownloadsIndexRoute = DownloadsIndexImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => rootRoute,
} as any)

const DonateIndexRoute = DonateIndexImport.update({
  id: '/donate/',
  path: '/donate/',
  getParentRoute: () => rootRoute,
} as any)

const ContactIndexRoute = ContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRoute,
} as any)

const AboutCfoIndexRoute = AboutCfoIndexImport.update({
  id: '/about/cfo/',
  path: '/about/cfo/',
  getParentRoute: () => rootRoute,
} as any)

const AboutBalinkbayanIndexRoute = AboutBalinkbayanIndexImport.update({
  id: '/about/balinkbayan/',
  path: '/about/balinkbayan/',
  getParentRoute: () => rootRoute,
} as any)

const StartBusinessInvestmentOpAgricultureRoute =
  StartBusinessInvestmentOpAgricultureImport.update({
    id: '/start-business/investment-op/agriculture',
    path: '/start-business/investment-op/agriculture',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexImport
      parentRoute: typeof rootRoute
    }
    '/donate/': {
      id: '/donate/'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateIndexImport
      parentRoute: typeof rootRoute
    }
    '/downloads/': {
      id: '/downloads/'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsIndexImport
      parentRoute: typeof rootRoute
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsIndexImport
      parentRoute: typeof rootRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesIndexImport
      parentRoute: typeof rootRoute
    }
    '/start-business/': {
      id: '/start-business/'
      path: '/start-business'
      fullPath: '/start-business'
      preLoaderRoute: typeof StartBusinessIndexImport
      parentRoute: typeof rootRoute
    }
    '/start-business/investment-op/agriculture': {
      id: '/start-business/investment-op/agriculture'
      path: '/start-business/investment-op/agriculture'
      fullPath: '/start-business/investment-op/agriculture'
      preLoaderRoute: typeof StartBusinessInvestmentOpAgricultureImport
      parentRoute: typeof rootRoute
    }
    '/about/balinkbayan/': {
      id: '/about/balinkbayan/'
      path: '/about/balinkbayan'
      fullPath: '/about/balinkbayan'
      preLoaderRoute: typeof AboutBalinkbayanIndexImport
      parentRoute: typeof rootRoute
    }
    '/about/cfo/': {
      id: '/about/cfo/'
      path: '/about/cfo'
      fullPath: '/about/cfo'
      preLoaderRoute: typeof AboutCfoIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactIndexRoute
  '/donate': typeof DonateIndexRoute
  '/downloads': typeof DownloadsIndexRoute
  '/news': typeof NewsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/start-business': typeof StartBusinessIndexRoute
  '/start-business/investment-op/agriculture': typeof StartBusinessInvestmentOpAgricultureRoute
  '/about/balinkbayan': typeof AboutBalinkbayanIndexRoute
  '/about/cfo': typeof AboutCfoIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactIndexRoute
  '/donate': typeof DonateIndexRoute
  '/downloads': typeof DownloadsIndexRoute
  '/news': typeof NewsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/start-business': typeof StartBusinessIndexRoute
  '/start-business/investment-op/agriculture': typeof StartBusinessInvestmentOpAgricultureRoute
  '/about/balinkbayan': typeof AboutBalinkbayanIndexRoute
  '/about/cfo': typeof AboutCfoIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contact/': typeof ContactIndexRoute
  '/donate/': typeof DonateIndexRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/start-business/': typeof StartBusinessIndexRoute
  '/start-business/investment-op/agriculture': typeof StartBusinessInvestmentOpAgricultureRoute
  '/about/balinkbayan/': typeof AboutBalinkbayanIndexRoute
  '/about/cfo/': typeof AboutCfoIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/donate'
    | '/downloads'
    | '/news'
    | '/services'
    | '/start-business'
    | '/start-business/investment-op/agriculture'
    | '/about/balinkbayan'
    | '/about/cfo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/donate'
    | '/downloads'
    | '/news'
    | '/services'
    | '/start-business'
    | '/start-business/investment-op/agriculture'
    | '/about/balinkbayan'
    | '/about/cfo'
  id:
    | '__root__'
    | '/'
    | '/contact/'
    | '/donate/'
    | '/downloads/'
    | '/news/'
    | '/services/'
    | '/start-business/'
    | '/start-business/investment-op/agriculture'
    | '/about/balinkbayan/'
    | '/about/cfo/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  DonateIndexRoute: typeof DonateIndexRoute
  DownloadsIndexRoute: typeof DownloadsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  StartBusinessIndexRoute: typeof StartBusinessIndexRoute
  StartBusinessInvestmentOpAgricultureRoute: typeof StartBusinessInvestmentOpAgricultureRoute
  AboutBalinkbayanIndexRoute: typeof AboutBalinkbayanIndexRoute
  AboutCfoIndexRoute: typeof AboutCfoIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  DonateIndexRoute: DonateIndexRoute,
  DownloadsIndexRoute: DownloadsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  StartBusinessIndexRoute: StartBusinessIndexRoute,
  StartBusinessInvestmentOpAgricultureRoute:
    StartBusinessInvestmentOpAgricultureRoute,
  AboutBalinkbayanIndexRoute: AboutBalinkbayanIndexRoute,
  AboutCfoIndexRoute: AboutCfoIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contact/",
        "/donate/",
        "/downloads/",
        "/news/",
        "/services/",
        "/start-business/",
        "/start-business/investment-op/agriculture",
        "/about/balinkbayan/",
        "/about/cfo/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contact/": {
      "filePath": "contact/index.tsx"
    },
    "/donate/": {
      "filePath": "donate/index.tsx"
    },
    "/downloads/": {
      "filePath": "downloads/index.tsx"
    },
    "/news/": {
      "filePath": "news/index.tsx"
    },
    "/services/": {
      "filePath": "services/index.tsx"
    },
    "/start-business/": {
      "filePath": "start-business/index.tsx"
    },
    "/start-business/investment-op/agriculture": {
      "filePath": "start-business/investment-op/agriculture.tsx"
    },
    "/about/balinkbayan/": {
      "filePath": "about/balinkbayan/index.tsx"
    },
    "/about/cfo/": {
      "filePath": "about/cfo/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
